'use client'

import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { createClient } from '@/lib/supabase/client'
import { 
  Sparkles, 
  Database, 
  Activity, 
  RotateCcw, 
  Trash2, 
  Plus, 
  Layers,
  ChevronRight,
  Flame,
  CheckCircle,
  Play
} from 'lucide-react'
import { getDbState, saveDbState, resetDbState } from '@/lib/supabase/mockDb'

export default function SandboxPage() {
  const [dbState, setDbState] = useState<any>(null)
  const [selectedTable, setSelectedTable] = useState<string>('profiles')
  const [isAnimating, setIsAnimating] = useState(false)
  const [springConfig, setSpringConfig] = useState({ stiffness: 100, damping: 10 })
  const [animationType, setAnimationType] = useState<'spring' | 'bounce' | 'fade'>('spring')
  const supabase = createClient()

  useEffect(() => {
    setDbState(getDbState())
  }, [])

  const handleReset = () => {
    if (confirm('Reset mock database?')) {
      resetDbState()
      setDbState(getDbState())
    }
  }

  const deleteRow = (table: string, id: string) => {
    const state = { ...dbState }
    state[table] = state[table].filter((row: any) => row.id !== id)
    saveDbState(state)
    setDbState(state)
  }

  const addMockItem = (table: string) => {
    const state = { ...dbState }
    let newItem = {}
    if (table === 'profiles') {
      newItem = {
        id: `mock-user-${Math.random().toString(36).substring(2, 6)}`,
        full_name: `Sandbox User ${state.profiles.length + 1}`,
        role: 'student',
        email: `sandbox-${state.profiles.length + 1}@university.edu`
      }
    } else if (table === 'projects') {
      newItem = {
        id: `mock-proj-${Math.random().toString(36).substring(2, 6)}`,
        title: `Sandbox Project ${state.projects.length + 1}`,
        description: 'Autogenerated sandbox testing project metadata.',
        student_id: 'demo-student-id',
        instructor_id: 'demo-instructor-id',
        industry_partner_id: 'demo-industry-id',
        status: 'pending',
        is_recommended: false,
        created_at: new Date().toISOString()
      }
    } else if (table === 'notifications') {
      newItem = {
        id: `mock-notif-${Math.random().toString(36).substring(2, 6)}`,
        user_id: 'demo-student-id',
        title: 'New Sandbox Notification',
        message: 'This is a test notification generated in the sandbox environment.',
        type: 'system',
        is_read: false,
        created_at: new Date().toISOString()
      }
    } else {
      newItem = {
        id: `mock-item-${Math.random().toString(36).substring(2, 6)}`,
        created_at: new Date().toISOString()
      }
    }
    state[table] = [...state[table], newItem]
    saveDbState(state)
    setDbState(state)
  }

  const getTransition = (): any => {
    if (animationType === 'spring') {
      return { type: 'spring', stiffness: springConfig.stiffness, damping: springConfig.damping }
    }
    if (animationType === 'bounce') {
      return { type: 'spring', bounce: 0.6 }
    }
    return { duration: 0.5, ease: 'easeInOut' }
  }

  return (
    <div className="min-h-screen bg-[#020617] text-white p-8 md:p-12 relative overflow-hidden font-sans">
      {/* Background Glows */}
      <div className="absolute top-[-20%] left-[-10%] w-[60%] h-[50%] bg-blue-600/10 blur-[150px] rounded-full pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-indigo-600/10 blur-[150px] rounded-full pointer-events-none" />

      <div className="max-w-7xl mx-auto z-10 relative">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12 border-b border-white/5 pb-8">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center shadow-lg shadow-blue-500/20">
              <Sparkles className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-3xl font-black tracking-tight">Development Sandbox</h1>
              <p className="text-slate-400 text-sm mt-1">Interact with Supabase mock database state & test Framer Motion animations.</p>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            <button 
              onClick={handleReset}
              className="px-4 py-2.5 bg-white/5 border border-white/10 hover:border-white/20 text-slate-300 hover:text-white rounded-xl text-xs font-bold transition-all flex items-center gap-2 cursor-pointer"
            >
              <RotateCcw className="w-4 h-4" />
              Reset DB State
            </button>
            <button 
              onClick={() => window.location.href = '/'}
              className="px-5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-bold shadow-lg shadow-blue-600/20 transition-all cursor-pointer"
            >
              Return Home
            </button>
          </div>
        </div>

        {/* Dashboard Grid */}
        <div className="grid lg:grid-cols-2 gap-10">
          
          {/* Column 1: Animation Lab */}
          <div className="space-y-8">
            <div className="bg-white/5 border border-white/10 rounded-[2.5rem] p-8 backdrop-blur-xl">
              <h2 className="text-xl font-bold flex items-center gap-2 mb-6">
                <Activity className="w-5 h-5 text-blue-400" />
                Framer Motion Laboratory
              </h2>

              {/* Controls */}
              <div className="grid grid-cols-3 gap-3 mb-8">
                {(['spring', 'bounce', 'fade'] as const).map((t) => (
                  <button
                    key={t}
                    onClick={() => setAnimationType(t)}
                    className={`py-2 rounded-xl text-xs font-bold border transition-all cursor-pointer ${
                      animationType === t 
                        ? 'bg-blue-600 border-blue-500 text-white shadow-md' 
                        : 'bg-white/5 border-white/5 text-slate-400 hover:text-white'
                    }`}
                  >
                    {t.toUpperCase()}
                  </button>
                ))}
              </div>

              {animationType === 'spring' && (
                <div className="space-y-4 mb-8 bg-slate-950/40 p-4 rounded-2xl border border-white/5">
                  <div>
                    <div className="flex justify-between text-xs font-bold text-slate-400 mb-1">
                      <span>STIFFNESS</span>
                      <span className="text-white">{springConfig.stiffness}</span>
                    </div>
                    <input 
                      type="range" min="10" max="500" 
                      value={springConfig.stiffness}
                      onChange={(e) => setSpringConfig({ ...springConfig, stiffness: parseInt(e.target.value) })}
                      className="w-full h-1 bg-white/10 rounded-lg appearance-none cursor-pointer accent-blue-500"
                    />
                  </div>
                  <div>
                    <div className="flex justify-between text-xs font-bold text-slate-400 mb-1">
                      <span>DAMPING</span>
                      <span className="text-white">{springConfig.damping}</span>
                    </div>
                    <input 
                      type="range" min="1" max="50" 
                      value={springConfig.damping}
                      onChange={(e) => setSpringConfig({ ...springConfig, damping: parseInt(e.target.value) })}
                      className="w-full h-1 bg-white/10 rounded-lg appearance-none cursor-pointer accent-blue-500"
                    />
                  </div>
                </div>
              )}

              {/* Animation Showcase Area */}
              <div className="h-64 bg-slate-950/60 border border-white/10 rounded-3xl flex items-center justify-center overflow-hidden relative group">
                <AnimatePresence mode="wait">
                  {!isAnimating ? (
                    <motion.div
                      key="static"
                      initial={{ scale: 0.8, opacity: 0 }}
                      animate={{ scale: 1, opacity: 1 }}
                      exit={{ scale: 0.8, opacity: 0 }}
                      className="flex flex-col items-center gap-4"
                    >
                      <div className="w-16 h-16 bg-gradient-to-tr from-blue-500 to-indigo-600 rounded-3xl flex items-center justify-center shadow-lg">
                        <Flame className="w-8 h-8 text-white" />
                      </div>
                      <button 
                        onClick={() => setIsAnimating(true)}
                        className="flex items-center gap-2 px-5 py-2.5 bg-white text-slate-950 rounded-full font-bold text-xs hover:scale-105 transition-transform"
                      >
                        <Play className="w-3.5 h-3.5 fill-current" />
                        Trigger Animation Loop
                      </button>
                    </motion.div>
                  ) : (
                    <motion.div
                      key="animating"
                      initial={{ x: -200, scale: 0.5, rotate: -45, opacity: 0 }}
                      animate={{ x: 0, scale: 1.2, rotate: 360, opacity: 1 }}
                      exit={{ x: 200, scale: 0.5, rotate: 720, opacity: 0 }}
                      transition={getTransition()}
                      onAnimationComplete={() => setTimeout(() => setIsAnimating(false), 800)}
                      className="w-20 h-20 bg-gradient-to-tr from-cyan-400 to-blue-600 rounded-[2rem] flex items-center justify-center shadow-2xl shadow-cyan-500/20"
                    >
                      <Sparkles className="w-8 h-8 text-white" />
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </div>

            {/* Micro-Interaction Playground */}
            <div className="bg-white/5 border border-white/10 rounded-[2.5rem] p-8 backdrop-blur-xl">
              <h3 className="font-bold text-lg mb-4">Physics Card Dragger</h3>
              <p className="text-xs text-slate-500 mb-6">Drag the card around. It will snap back to the center using spring physics.</p>
              
              <div className="h-60 bg-slate-950/40 rounded-3xl border border-white/5 flex items-center justify-center relative overflow-hidden">
                <motion.div
                  drag
                  dragConstraints={{ top: -80, bottom: 80, left: -150, right: 150 }}
                  dragElastic={0.2}
                  whileDrag={{ scale: 1.08, rotate: 2 }}
                  whileHover={{ scale: 1.02 }}
                  className="w-48 p-5 bg-white/5 border border-white/10 rounded-2xl shadow-2xl backdrop-blur-md cursor-grab active:cursor-grabbing text-center"
                >
                  <Layers className="w-6 h-6 text-indigo-400 mx-auto mb-2" />
                  <div className="text-xs font-black tracking-widest uppercase text-slate-500">Draggable Card</div>
                  <div className="text-sm font-bold text-white mt-1">Physics Engine Active</div>
                </motion.div>
              </div>
            </div>
          </div>

          {/* Column 2: Supabase Mock Database Inspector */}
          <div className="bg-white/5 border border-white/10 rounded-[2.5rem] p-8 backdrop-blur-xl flex flex-col">
            <h2 className="text-xl font-bold flex items-center gap-2 mb-6">
              <Database className="w-5 h-5 text-indigo-400" />
              Mock DB Inspector
            </h2>

            {/* Table selector */}
            <div className="flex gap-2 mb-6 border-b border-white/5 pb-4 overflow-x-auto">
              {['profiles', 'projects', 'deliverables', 'messages', 'notifications'].map((t) => (
                <button
                  key={t}
                  onClick={() => setSelectedTable(t)}
                  className={`px-4 py-2 rounded-xl text-xs font-bold transition-all shrink-0 cursor-pointer ${
                    selectedTable === t 
                      ? 'bg-indigo-600/20 border border-indigo-500/30 text-indigo-400' 
                      : 'text-slate-500 hover:text-slate-300'
                  }`}
                >
                  {t.toUpperCase()}
                </button>
              ))}
            </div>

            {/* Actions for current table */}
            <div className="flex items-center justify-between mb-4">
              <div className="text-xs text-slate-500 font-bold uppercase tracking-widest">
                {dbState && dbState[selectedTable] ? dbState[selectedTable].length : 0} Rows
              </div>
              <button 
                onClick={() => addMockItem(selectedTable)}
                className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer"
              >
                <Plus className="w-3.5 h-3.5" />
                Add Mock Row
              </button>
            </div>

            {/* Table list view */}
            <div className="flex-1 max-h-[500px] overflow-y-auto space-y-3 custom-scrollbar pr-2">
              <AnimatePresence mode="popLayout">
                {dbState && dbState[selectedTable] && dbState[selectedTable].length > 0 ? (
                  dbState[selectedTable].map((row: any) => (
                    <motion.div
                      layout
                      initial={{ opacity: 0, y: 15 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, x: -50 }}
                      key={row.id}
                      className="p-4 bg-slate-950/40 border border-white/5 rounded-2xl flex items-center justify-between gap-4 group"
                    >
                      <div className="overflow-hidden">
                        <div className="text-xs text-slate-400 font-bold font-mono truncate">{row.id}</div>
                        <div className="text-sm font-bold text-white mt-1 truncate">
                          {row.full_name || row.title || row.content || row.message || 'Custom Row Details'}
                        </div>
                        {row.role && <div className="text-[10px] uppercase text-indigo-400 font-black tracking-widest mt-1">{row.role}</div>}
                        {row.status && <div className="text-[10px] uppercase text-green-400 font-black tracking-widest mt-1">Status: {row.status}</div>}
                      </div>

                      <button
                        onClick={() => deleteRow(selectedTable, row.id)}
                        className="p-2 bg-red-500/10 hover:bg-red-500/20 text-red-400 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer shrink-0"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </motion.div>
                  ))
                ) : (
                  <div className="h-48 border border-dashed border-white/5 rounded-2xl flex flex-col items-center justify-center text-slate-600 text-sm">
                    <Database className="w-8 h-8 mb-2" />
                    No rows in mock database table
                  </div>
                )}
              </AnimatePresence>
            </div>

          </div>

        </div>

      </div>
    </div>
  )
}
